SELECT
    NUM_UC_HCAI AS uc,
    INDIC_FAT_HCAI AS faturado,
    CASE
        WHEN INDIC_REG_ORIG_INTRP_HCAI = 'P' THEN 'CSL'
        WHEN INDIC_REG_ORIG_INTRP_HCAI = 'L' THEN 'NRT'
        WHEN INDIC_REG_ORIG_INTRP_HCAI = 'M' THEN 'NRO'
        WHEN INDIC_REG_ORIG_INTRP_HCAI = 'C' THEN 'LES'
        WHEN INDIC_REG_ORIG_INTRP_HCAI = 'V' THEN 'OES'
        ELSE 'COPEL'
    END AS regional
FROM iqs.HIST_CONS_AFETADO_INTERRUPCAO hcai
WHERE to_char(hcai.DATA_INTRP_HCAI, 'yyyymm') = :anomes
  AND INDIC_UC_ACESS_HCAI = 'N'
