SELECT
    CASE 
        WHEN GROUPING(rd.SIGLA_RDIS) = 1 THEN 'COPEL'
        ELSE rd.SIGLA_RDIS 
    END AS REGIONAL_TOTAL,
    COUNT(ue.ISN_UC) AS UC,
    COUNT(CASE WHEN ue.INDIC_LOCAL_UC = 'U' THEN 1 END) AS UC_URBANA,
    COUNT(CASE WHEN ue.INDIC_LOCAL_UC = 'R' THEN 1 END) AS UC_RURAL,
    SUM(NVL(ue.VAL_BASE_CALC_COMPEN_UC, 0)) AS VRC,
    SUM(CASE WHEN ue.INDIC_LOCAL_UC = 'U' THEN NVL(ue.VAL_BASE_CALC_COMPEN_UC, 0) ELSE 0 END) AS VRC_URBANO,
    SUM(CASE WHEN ue.INDIC_LOCAL_UC = 'R' THEN NVL(ue.VAL_BASE_CALC_COMPEN_UC, 0) ELSE 0 END) AS VRC_RURAL
FROM cis.UC_ENERGIA ue
LEFT JOIN cis.LOCALIDADE l
    ON ue.COD_LOCAL_UC = l.COD_LOCAL
LEFT JOIN cis.seccional_distribuicao sc
    ON l.COD_SECCION_DISTR_LOCAL = sc.COD_SDIS
LEFT JOIN cis.REGIONAL_DISTRIBUICAO rd 
    ON sc.COD_REG_DISTR_SDIS = rd.COD_RDIS       
WHERE ue.TIPO_SIT_UC IN ('LG', 'CR')
GROUP BY ROLLUP (rd.SIGLA_RDIS)
ORDER BY 
    GROUPING(rd.SIGLA_RDIS), 
    rd.SIGLA_RDIS;